name: Build imagem
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: "export DOCKER_CONTENT_TRUST=1"
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Análise estática
        uses: dominikh/staticcheck-action@v1.2.0
      -
        name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Setup Build
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/security-focused-pipeline:latest