name: Build imagem
run-name: Pipeline Focada em segurança 🔒
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: "export DOCKER_CONTENT_TRUST=1"
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup go
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: "1.20.x"
      -
        name: Teste unitário
        run: "go test"  
      -
        name: Análise estática
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
      -
        name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Setup Build
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/security-focused-pipeline:latest
      - 
        name: Scan ZAP
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: https://security-focused-pipeline-production.up.railway.app
      